#!/usr/bin/env python

import os
import sys
import argparse

import dpath.util
import json

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('--keys', '-k', action='store_true')
    p.add_argument('--values', '-v', action='store_true')
    p.add_argument('--pretty', '-p', action='store_true')
    p.add_argument('paths', nargs='*')
    return p.parse_args()

def main():
    args = parse_args()

    cfg = json.load(sys.stdin)

    for pathexp in args.paths:
        if args.pretty:
            print json.dumps(dpath.util.search(cfg, pathexp), indent=4)
        else:
            for path,val in dpath.util.search(cfg, pathexp, True):
                if args.keys:
                    print path
                elif args.values:
                    print val
                else:
                    print path, val

if __name__ == '__main__':
    main()


