#!/usr/bin/env python

import os
import sys
import argparse

import dpath.util
import json

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('vars', nargs='*')
    return p.parse_args()

def main():
    args = parse_args()

    cfg = {}

    for var in args.vars:
        path,val = var.split('=', 1)
        if val == '[]':
            val=[]
        dpath.util.new(cfg, path, val)

    print json.dumps(cfg, indent=4)

if __name__ == '__main__':
    main()


